version: '3.8'
name: mysql-playground

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: playground
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    user: mysql
    ports:
      - "3306:3306"
    volumes:
      # - ./data:/var/lib/mysql:rw
      - ./init:/docker-entrypoint-initdb.d:rw