version: "3.8"
name: mysql-playground

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    user: mysql
    ports:
      - "3306:3306"
    volumes:
      # - ./data:/var/lib/mysql:rw
      - ./current_case/init:/docker-entrypoint-initdb.d:rw
