CREATE TABLE `user`(
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `email` VARCHAR(254) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `age` INT NOT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
);